# Default values for links-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2


image:
  repository: 449814578585.dkr.ecr.eu-north-1.amazonaws.com/linkspace
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.11


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.org/proxy-connect-timeout: "90s"
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: linksspaces.tk
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: secrettls
     hosts:
       - linksspaces.tk



#secret from AWS secrets Manager
Secretdb:
  enabled: true
  name: secretsmanagermongodb
  region: eu-north-1
  dataFrom: mongodb
  
#secret from AWS secrets Manager
Secrettls:
  enabled: true
  name: secrettls
  region: eu-north-1
  dataFrom: tls

configmap:
  name: configmap
  hostname: mongodb-0.mongodb-headless,mongodb-1.mongodb-headless,mongodb-2.mongodb-headless
  urlsuffix: authSource=admin

#ca
ClusterIssuer:
  enabled: true
  name: letsencrypt-production
  server: https://acme-v02.api.letsencrypt.org/directory
  email: ofer.rvd@gmail.com
  nameprivateKey: letsencrypt-production
  solveringresssclass: nginx


resources: 
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 10m
      memory: 50Mi


nodeSelector: {}

tolerations: []

affinity: {}


#values to chart mongodb
mongodb:
  fullnameOverride: mongodb
  nameOverride: mongodb
  auth:
    enabled: true
    rootUser: admin
    rootPassword: password
  architecture: replicaset
  useStatefulSet: true
  replicaCount: 3
  arbiter:
    enabled: false
  metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: "monitoring"

#values to chart nginx
ingress-nginx:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: "monitoring"
    
