
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "links-app.fullname" . }}
  labels: 
    {{- include "links-app.labels" . | nindent 6   }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "links-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "links-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
            name: configmap
          - secretRef:
            name: secretsmanagermongodb
        resources: {{ toYaml .Values.resources | indent 10 }}