{{- if .Values.Secretdb.enabled -}}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Values.Secretdb.name }}
spec:
  backendType: secretsManager
  region: {{ .Values.Secretdb.region }}
  dataFrom:
    - {{ .Values.Secretdb.dataFrom }}
{{- end }}