{{- if .Values.Secrettls.enabled -}}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Values.Secrettls.name }}
spec:
  backendType: secretsManager
  region: {{ .Values.Secrettls.region }}
  dataFrom:
    - {{ .Values.Secrettls.dataFrom }}
  type: kubernetes.io/tls
{{- end }}