apiVersion: v1
kind: Service
metadata:
  name: {{ include "links-app.fullname" . }}
  labels:
    {{- include "links-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP

  selector:
    {{- include "links-app.selectorLabels" . | nindent 4 }}
