apiVersion: v1
kind: Service
metadata:
  name: {{ include "applink.fullname" . }}
  labels:
    {{- include "applink.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 
      targetPort: 5000
      protocol: TCP
      port: {{ .Values.service.port }}

  selector:
    {{- include "applink.selectorLabels" . | nindent 4 }}
